"""empty message

Revision ID: c8cc8bf588f6
Revises: b83698d1932b
Create Date: 2024-02-16 15:17:02.249122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8cc8bf588f6'
down_revision = 'b83698d1932b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_chambre', sa.Integer(), nullable=True))
        batch_op.drop_constraint('reservation_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chambre', ['id_chambre'], ['id'])
        batch_op.drop_column('id_chanbre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_chanbre', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reservation_ibfk_1', 'chambre', ['id_chanbre'], ['id'])
        batch_op.drop_column('id_chambre')

    # ### end Alembic commands ###
